-- ============================================================================
-- column_tde.sql - Encrypting Individual Columns with TDE
-- ============================================================================
-- This script demonstrates how to encrypt specific columns in Oracle tables
-- using Transparent Data Encryption (TDE).
--
-- Prerequisites:
--   - TDE wallet must be configured and open (see setup_tde.sql)
--   - Appropriate tablespace and user schema must exist
--
-- Usage:
--   sqlplus app_user/app_password @column_tde.sql
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET VERIFY OFF

-- ============================================================================
-- Step 1: Create a Demo Schema and Table
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 1: Creating Demo Schema and Table ===');
  
  -- Create a dedicated tablespace for TDE demo (optional)
  EXECUTE IMMEDIATE 'CREATE TABLESPACE tde_demo_data DATAFILE ''/opt/oracle/oradata/orcl/tde_demo_data.dbf'' SIZE 100M AUTOEXTEND ON NEXT 10M';
  DBMS_OUTPUT.PUT_LINE('Tablespace created: tde_demo_data');
  
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1537 THEN
      DBMS_OUTPUT.PUT_LINE('Tablespace tde_demo_data already exists. Skipping creation.');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Warning: ' || SQLERRM);
    END IF;
END;
/

-- Create demo user
CREATE USER tde_demo_user IDENTIFIED BY "DemoUser123!" DEFAULT TABLESPACE tde_demo_data QUOTA UNLIMITED ON tde_demo_data;

-- Grant necessary privileges
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO tde_demo_user;

-- ============================================================================
-- Step 2: Create Employee Table with Encrypted Columns
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 2: Creating Employee Table with Encrypted Columns ===');
  
  EXECUTE IMMEDIATE '
    CREATE TABLE tde_demo_user.employees (
      employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name    VARCHAR2(50) NOT NULL,
      last_name     VARCHAR2(50) NOT NULL,
      email         VARCHAR2(100) UNIQUE,
      phone         VARCHAR2(20),
      salary        NUMBER(10,2),
      ssn           VARCHAR2(11) ENCRYPT NO SALT,
      credit_card   VARCHAR2(19) ENCRYPT,
      salary        NUMBER(10,2) ENCRYPT,
      hire_date     DATE DEFAULT SYSDATE,
      department    VARCHAR2(50)
    )';
  
  DBMS_OUTPUT.PUT_LINE('Table created with encrypted columns:');
  DBMS_OUTPUT.PUT_LINE('  - ssn: Encrypted without salt (supports equality searches)');
  DBMS_OUTPUT.PUT_LINE('  - credit_card: Encrypted with salt (higher security)');
  DBMS_OUTPUT.PUT_LINE('  - salary: Encrypted (sensitive compensation data)');
  
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('Table already exists. Skipping creation.');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Error creating table: ' || SQLERRM);
      RAISE;
    END IF;
END;
/

-- ============================================================================
-- Step 3: Insert Sample Data
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 3: Inserting Sample Data ===');
  
  EXECUTE IMMEDIATE '
    INSERT INTO tde_demo_user.employees 
    (first_name, last_name, email, phone, salary, ssn, credit_card, department)
    VALUES 
    (''John'', ''Doe'', ''john.doe@company.com'', ''555-0101'', 75000.00, ''123-45-6789'', ''4111-1111-1111-1111'', ''Engineering''),
    (''Jane'', ''Smith'', ''jane.smith@company.com'', ''555-0102'', 85000.00, ''987-65-4321'', ''5500-0000-0000-0004'', ''Marketing''),
    (''Bob'', ''Johnson'', ''bob.johnson@company.com'', ''555-0103'', 92000.00, ''456-78-9012'', ''3782-822463-10005'', ''Finance'')
  ';
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('3 employee records inserted.');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inserting data: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 4: Query Encrypted Data (Transparent Decryption)
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 4: Querying Encrypted Data ===');
  DBMS_OUTPUT.PUT_LINE('TDE automatically decrypts data when queried by authorized users.');
  DBMS_OUTPUT.PUT_LINE('');
  
  FOR rec IN (
    SELECT employee_id, first_name, last_name, ssn, 
           SUBSTR(credit_card, 1, 4) || '****' || SUBSTR(credit_card, -4) AS masked_card,
           salary, department
    FROM tde_demo_user.employees
    ORDER BY employee_id
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      'ID: ' || rec.employee_id || 
      ', Name: ' || rec.first_name || ' ' || rec.last_name ||
      ', SSN: ' || rec.ssn ||
      ', Card: ' || rec.masked_card ||
      ', Salary: ' || rec.salary ||
      ', Dept: ' || rec.department
    );
  END LOOP;
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error querying data: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 5: Demonstrate Search on Encrypted Column (NO SALT)
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 5: Searching Encrypted Column (NO SALT) ===');
  
  DECLARE
    v_ssn VARCHAR2(11) := '123-45-6789';
    v_name VARCHAR2(100);
  BEGIN
    -- This works because ssn was encrypted WITHOUT salt
    SELECT first_name || ' ' || last_name INTO v_name
    FROM tde_demo_user.employees
    WHERE ssn = v_ssn;
    
    DBMS_OUTPUT.PUT_LINE('Found employee with SSN ' || v_ssn || ': ' || v_name);
    
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('No employee found with SSN: ' || v_ssn);
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Search error: ' || SQLERRM);
  END;
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 6: Verify Encryption at Rest
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 6: Verifying Encryption at Rest ===');
  
  -- Check which columns are encrypted
  DBMS_OUTPUT.PUT_LINE('Encrypted columns in employees table:');
  
  FOR col IN (
    SELECT column_name, encryption_alg, salt
    FROM dba_encrypted_columns
    WHERE owner = 'TDE_DEMO_USER'
      AND table_name = 'EMPLOYEES'
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      '  Column: ' || col.column_name ||
      ', Algorithm: ' || col.encryption_alg ||
      ', Salt: ' || CASE WHEN col.salt = 'YES' THEN 'Yes' ELSE 'No' END
    );
  END LOOP;
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error checking encryption: ' || SQLERRM);
END;
/

-- ============================================================================
-- Summary
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('========================================');
  DBMS_OUTPUT.PUT_LINE('Column TDE Summary');
  DBMS_OUTPUT.PUT_LINE('========================================');
  DBMS_OUTPUT.PUT_LINE('1. Table: tde_demo_user.employees');
  DBMS_OUTPUT.PUT_LINE('2. Encrypted columns: ssn, credit_card, salary');
  DBMS_OUTPUT.PUT_LINE('3. Data is transparently encrypted at rest');
  DBMS_OUTPUT.PUT_LINE('4. Authorized users see decrypted data automatically');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('ENCRYPT options:');
  DBMS_OUTPUT.PUT_LINE('  - ENCRYPT: Encrypts with salt (higher security)');
  DBMS_OUTPUT.PUT_LINE('  - ENCRYPT NO SALT: Encrypts without salt (supports indexing/search)');
  DBMS_OUTPUT.PUT_LINE('========================================');
END;
/
