-- ============================================================================
-- tablespace_tde.sql - Creating Encrypted Tablespaces
-- ============================================================================
-- This script demonstrates how to create and use encrypted tablespaces
-- in Oracle Database using Transparent Data Encryption (TDE).
--
-- All data in an encrypted tablespace is automatically encrypted at rest.
-- This provides a higher level of security than column-level encryption.
--
-- Prerequisites:
--   - TDE wallet must be configured and open (see setup_tde.sql)
--   - DBA privileges required
--
-- Usage:
--   sqlplus / as sysdba @tablespace_tde.sql
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET VERIFY OFF

-- ============================================================================
-- Step 1: Verify Wallet is Open
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 1: Verifying Wallet Status ===');
  
  DECLARE
    v_status VARCHAR2(30);
  BEGIN
    SELECT status INTO v_status FROM v$encryption_wallet;
    
    IF v_status = 'OPEN' THEN
      DBMS_OUTPUT.PUT_LINE('Wallet is OPEN. Proceeding with encrypted tablespace creation.');
    ELSE
      DBMS_OUTPUT.PUT_LINE('WARNING: Wallet is NOT open (' || v_status || ').');
      DBMS_OUTPUT.PUT_LINE('Please open the wallet before creating encrypted tablespaces.');
      RAISE_APPLICATION_ERROR(-20001, 'Wallet must be open to create encrypted tablespace');
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('ERROR: Wallet not found. Please run setup_tde.sql first.');
      RAISE_APPLICATION_ERROR(-20002, 'Wallet not configured');
    WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
      RAISE;
  END;
END;
/

-- ============================================================================
-- Step 2: Create Encrypted Tablespace
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 2: Creating Encrypted Tablespace ===');
  
  -- Create an encrypted tablespace with AES256 encryption
  EXECUTE IMMEDIATE '
    CREATE TABLESPACE tde_encrypted_data
    DATAFILE ''/opt/oracle/oradata/orcl/tde_encrypted_data.dbf''
    SIZE 100M AUTOEXTEND ON NEXT 10M
    ENCRYPTION USING ''AES256''
    DEFAULT STORAGE (ENCRYPT)
  ';
  
  DBMS_OUTPUT.PUT_LINE('Encrypted tablespace created:');
  DBMS_OUTPUT.PUT_LINE('  - Name: tde_encrypted_data');
  DBMS_OUTPUT.PUT_LINE('  - Encryption Algorithm: AES256');
  DBMS_OUTPUT.PUT_LINE('  - Datafile: /opt/oracle/oradata/orcl/tde_encrypted_data.dbf');
  DBMS_OUTPUT.PUT_LINE('  - Auto-extend: Enabled (10M increments)');
  
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1537 THEN
      DBMS_OUTPUT.PUT_LINE('Tablespace tde_encrypted_data already exists. Skipping creation.');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Error creating encrypted tablespace: ' || SQLERRM);
      RAISE;
    END IF;
END;
/

-- ============================================================================
-- Step 3: Create Demo User with Encrypted Tablespace
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 3: Creating Demo User ===');
  
  -- Create user with encrypted tablespace as default
  EXECUTE IMMEDIATE '
    CREATE USER tde_encrypted_user
    IDENTIFIED BY "EncryptedUser123!"
    DEFAULT TABLESPACE tde_encrypted_data
    QUOTA UNLIMITED ON tde_encrypted_data
  ';
  
  -- Grant necessary privileges
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO tde_encrypted_user';
  
  DBMS_OUTPUT.PUT_LINE('User created: tde_encrypted_user');
  DBMS_OUTPUT.PUT_LINE('Default tablespace: tde_encrypted_data (encrypted)');
  
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1920 THEN
      DBMS_OUTPUT.PUT_LINE('User tde_encrypted_user already exists. Skipping creation.');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Error creating user: ' || SQLERRM);
      RAISE;
    END IF;
END;
/

-- ============================================================================
-- Step 4: Create Table in Encrypted Tablespace
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 4: Creating Table in Encrypted Tablespace ===');
  
  EXECUTE IMMEDIATE '
    CREATE TABLE tde_encrypted_user.sensitive_data (
      id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      patient_id  VARCHAR2(20) NOT NULL,
      diagnosis   VARCHAR2(200),
      notes       CLOB,
      created_at  DATE DEFAULT SYSDATE
    ) TABLESPACE tde_encrypted_data
  ';
  
  DBMS_OUTPUT.PUT_LINE('Table created in encrypted tablespace:');
  DBMS_OUTPUT.PUT_LINE('  - Owner: tde_encrypted_user');
  DBMS_OUTPUT.PUT_LINE('  - Table: sensitive_data');
  DBMS_OUTPUT.PUT_LINE('  - All data automatically encrypted at rest');
  
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('Table already exists. Skipping creation.');
    ELSE
      DBMS_OUTPUT.PUT_LINE('Error creating table: ' || SQLERRM);
      RAISE;
    END IF;
END;
/

-- ============================================================================
-- Step 5: Insert and Query Data
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 5: Inserting and Querying Data ===');
  
  -- Insert sample data
  EXECUTE IMMEDIATE '
    INSERT INTO tde_encrypted_user.sensitive_data 
    (patient_id, diagnosis, notes)
    VALUES 
    (''PAT-001'', ''Type 2 Diabetes'', ''Patient started on metformin 500mg twice daily.''),
    (''PAT-002'', ''Hypertension'', ''Blood pressure monitoring recommended.''),
    (''PAT-003'', ''Asthma'', ''Inhaler prescribed. Follow-up in 3 months.''
  ';
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('3 records inserted into encrypted tablespace.');
  
  -- Query data (transparent decryption)
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Querying data (transparently decrypted):');
  
  FOR rec IN (
    SELECT patient_id, diagnosis, SUBSTR(notes, 1, 50) AS note_preview
    FROM tde_encrypted_user.sensitive_data
    ORDER BY id
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      '  Patient: ' || rec.patient_id ||
      ', Diagnosis: ' || rec.diagnosis ||
      ', Notes: ' || rec.note_preview || '...'
    );
  END LOOP;
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error inserting/querying data: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 6: Verify Tablespace Encryption
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 6: Verifying Tablespace Encryption ===');
  
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Encrypted tablespaces in the database:');
  
  FOR ts IN (
    SELECT tablespace_name, encryption_alg, status
    FROM dba_tablespaces
    WHERE encryption_algorithm IS NOT NULL
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      '  Tablespace: ' || ts.tablespace_name ||
      ', Algorithm: ' || ts.encryption_alg ||
      ', Status: ' || ts.status
    );
  END LOOP;
  
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Datafiles in encrypted tablespaces:');
  
  FOR df IN (
    SELECT file_name, tablespace_name
    FROM dba_data_files
    WHERE tablespace_name = 'TDE_ENCRYPTED_DATA'
  ) LOOP
    DBMS_OUTPUT.PUT_LINE('  File: ' || df.file_name);
    DBMS_OUTPUT.PUT_LINE('  Tablespace: ' || df.tablespace_name);
  END LOOP;
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error verifying encryption: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 7: Drop Encrypted Tablespace (Cleanup)
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 7: Cleanup Instructions ===');
  
  DBMS_OUTPUT.PUT_LINE('To drop the encrypted tablespace and clean up:');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('  -- Drop the user first');
  DBMS_OUTPUT.PUT_LINE('  DROP USER tde_encrypted_user CASCADE;');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('  -- Drop the encrypted tablespace');
  DBMS_OUTPUT.PUT_LINE('  DROP TABLESPACE tde_encrypted_data INCLUDING CONTENTS AND DATAFILES;');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('  -- Drop the demo tablespace if created');
  DBMS_OUTPUT.PUT_LINE('  DROP TABLESPACE tde_demo_data INCLUDING CONTENTS AND DATAFILES;');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

-- ============================================================================
-- Summary
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('========================================');
  DBMS_OUTPUT.PUT_LINE('Encrypted Tablespace Summary');
  DBMS_OUTPUT.PUT_LINE('========================================');
  DBMS_OUTPUT.PUT_LINE('1. Tablespace: tde_encrypted_data');
  DBMS_OUTPUT.PUT_LINE('2. Encryption: AES256');
  DBMS_OUTPUT.PUT_LINE('3. All data automatically encrypted at rest');
  DBMS_OUTPUT.PUT_LINE('4. No application changes required');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Benefits:');
  DBMS_OUTPUT.PUT_LINE('  - Complete transparency to applications');
  DBMS_OUTPUT.PUT_LINE('  - Encrypts all data in the tablespace');
  DBMS_OUTPUT.PUT_LINE('  - No column-by-column configuration needed');
  DBMS_OUTPUT.PUT_LINE('  - Supports all data types including LOBs');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Considerations:');
  DBMS_OUTPUT.PUT_LINE('  - Performance overhead: ~5-15%');
  DBMS_OUTPUT.PUT_LINE('  - Cannot encrypt existing data without reorganization');
  DBMS_OUTPUT.PUT_LINE('  - Wallet must be open for all operations');
  DBMS_OUTPUT.PUT_LINE('========================================');
END;
/
