-- ============================================================================
-- redaction_policies.sql - Creating and Managing Redaction Policies
-- ============================================================================
-- This script demonstrates how to create, manage, and test Oracle Data
-- Redaction policies using the DBMS_REDACT package.
--
-- Data Redaction provides real-time data masking at the application level,
-- ensuring sensitive data is hidden from unauthorized users without
-- modifying the underlying data.
--
-- Prerequisites:
--   - Oracle Database 12c or later
--   - DBMS_REDACT package installed (usually available by default)
--   - Appropriate privileges to create policies
--
-- Usage:
--   sqlplus app_user/app_password @redaction_policies.sql
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET VERIFY OFF

-- ============================================================================
-- Step 1: Create Demo Schema and Sample Data
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 1: Creating Demo Schema and Sample Data ===');
  
  -- Create demo user if not exists
  BEGIN
    EXECUTE IMMEDIATE 'CREATE USER redact_demo_user IDENTIFIED BY "DemoUser123!"';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION, CREATE TABLE TO redact_demo_user';
    DBMS_OUTPUT.PUT_LINE('Created user: redact_demo_user');
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -1920 THEN
        DBMS_OUTPUT.PUT_LINE('User redact_demo_user already exists.');
      ELSE
        RAISE;
      END IF;
  END;
  
  -- Create employees table with sensitive columns
  EXECUTE IMMEDIATE '
    CREATE TABLE redact_demo_user.employees (
      employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name    VARCHAR2(50) NOT NULL,
      last_name     VARCHAR2(50) NOT NULL,
      email         VARCHAR2(100),
      phone         VARCHAR2(20),
      ssn           VARCHAR2(11),
      salary        NUMBER(10,2),
      credit_card   VARCHAR2(19),
      hire_date     DATE DEFAULT SYSDATE
    )
  ';
  
  -- Insert sample data
  EXECUTE IMMEDIATE '
    INSERT INTO redact_demo_user.employees 
    (first_name, last_name, email, phone, ssn, salary, credit_card)
    VALUES 
    (''John'', ''Doe'', ''john.doe@company.com'', ''555-0101'', ''123-45-6789'', 75000.00, ''4111111111111111''),
    (''Jane'', ''Smith'', ''jane.smith@company.com'', ''555-0102'', ''987-65-4321'', 85000.00, ''5500000000000004''),
    (''Bob'', ''Johnson'', ''bob.johnson@company.com'', ''555-0103'', ''456-78-9012'', 92000.00, ''378282246310005''
  ';
  
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Created table and inserted 3 employee records.');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 2: Create Redaction Policies
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 2: Creating Redaction Policies ===');
  
  -- Policy 1: Full redaction for SSN (hide from all users)
  DBMS_REDACT.ADD_POLICY(
    object_schema   => 'REDACT_DEMO_USER',
    object_name     => 'EMPLOYEES',
    policy_name     => 'SSN_FULL_REDACTION',
    column_name     => 'SSN',
    expression      => '1=1',
    function_type   => DBMS_REDACT.FULL,
    function_params => NULL,
    policy_description => 'Full redaction of SSN for all users'
  );
  
  DBMS_OUTPUT.PUT_LINE('Policy created: SSN_FULL_REDACTION (Full redaction)');
  
  -- Policy 2: Partial redaction for salary
  DBMS_REDACT.ADD_POLICY(
    object_schema   => 'REDACT_DEMO_USER',
    object_name     => 'EMPLOYEES',
    policy_name     => 'SALARY_PARTIAL_REDACTION',
    column_name     => 'SALARY',
    expression      => '1=1',
    function_type   => DBMS_REDACT.PARTIAL,
    function_params => DBMS_REDACT.REDACT_PARTIAL(0, 5, '****', 0, 0),
    policy_description => 'Partial redaction of salary (show first 5 digits)'
  );
  
  DBMS_OUTPUT.PUT_LINE('Policy created: SALARY_PARTIAL_REDACTION (Partial redaction)');
  
  -- Policy 3: Regex-based redaction for email
  DBMS_REDACT.ADD_POLICY(
    object_schema   => 'REDACT_DEMO_USER',
    object_name     => 'EMPLOYEES',
    policy_name     => 'EMAIL_REGEX_REDACTION',
    column_name     => 'EMAIL',
    expression      => '1=1',
    function_type   => DBMS_REDACT.REGEX,
    function_params => DBMS_REDACT.REDACT_REGEX(
      '([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})',
      '\1**@**.**',
      1
    ),
    policy_description => 'Regex-based redaction of email addresses'
  );
  
  DBMS_OUTPUT.PUT_LINE('Policy created: EMAIL_REGEX_REDACTION (Regex redaction)');
  
  -- Policy 4: Conditional redaction based on user role
  DBMS_REDACT.ADD_POLICY(
    object_schema   => 'REDACT_DEMO_USER',
    object_name     => 'EMPLOYEES',
    policy_name     => 'CC_HR_ONLY_REDACTION',
    column_name     => 'CREDIT_CARD',
    expression      => 'SYS_CONTEXT(''USERENV'', ''SESSION_USER'') <> ''HR_ADMIN''',
    function_type   => DBMS_REDACT.FULL,
    function_params => NULL,
    policy_description => 'Full redaction of credit card for non-HR users'
  );
  
  DBMS_OUTPUT.PUT_LINE('Policy created: CC_HR_ONLY_REDACTION (Conditional redaction)');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error creating policies: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 3: Query Data with Redaction Applied
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 3: Querying Data with Redaction Applied ===');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Data is redacted in real-time based on policies:');
  DBMS_OUTPUT.PUT_LINE('');
  
  FOR rec IN (
    SELECT employee_id,
           first_name,
           last_name,
           email,
           phone,
           ssn,
           salary,
           credit_card
    FROM redact_demo_user.employees
    ORDER BY employee_id
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      'Employee #' || rec.employee_id || ': ' || rec.first_name || ' ' || rec.last_name ||
      ' | Email: ' || rec.email ||
      ' | SSN: ' || rec.ssn ||
      ' | Salary: ' || rec.salary ||
      ' | Card: ' || rec.credit_card
    );
  END LOOP;
  
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Notice: Sensitive data is masked according to policies.');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error querying data: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 4: List All Redaction Policies
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 4: Listing All Redaction Policies ===');
  DBMS_OUTPUT.PUT_LINE('');
  
  DBMS_OUTPUT.PUT_LINE('Active redaction policies:');
  
  FOR p IN (
    SELECT policy_name,
           object_schema,
           object_name,
           column_name,
           function_type,
           expression,
           enabled
    FROM redaction_policies
    WHERE object_schema = 'REDACT_DEMO_USER'
    ORDER BY policy_name
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(
      '  Policy: ' || p.policy_name ||
      ', Column: ' || p.column_name ||
      ', Type: ' || p.function_type ||
      ', Enabled: ' || CASE WHEN p.enabled = 1 THEN 'Yes' ELSE 'No' END
    );
    
    IF p.expression IS NOT NULL THEN
      DBMS_OUTPUT.PUT_LINE('    Expression: ' || p.expression);
    END IF;
  END LOOP;
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error listing policies: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 5: Enable/Disable Policies
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 5: Managing Policy States ===');
  DBMS_OUTPUT.PUT_LINE('');
  
  -- Disable a policy
  DBMS_REDACT.ALTER_POLICY(
    object_schema  => 'REDACT_DEMO_USER',
    object_name    => 'EMPLOYEES',
    policy_name    => 'SALARY_PARTIAL_REDACTION',
    action         => DBMS_REDACT.DISABLE
  );
  
  DBMS_OUTPUT.PUT_LINE('Policy disabled: SALARY_PARTIAL_REDACTION');
  DBMS_OUTPUT.PUT_LINE('Salary will now be visible to all users.');
  
  -- Re-enable the policy
  DBMS_REDACT.ALTER_POLICY(
    object_schema  => 'REDACT_DEMO_USER',
    object_name    => 'EMPLOYEES',
    policy_name    => 'SALARY_PARTIAL_REDACTION',
    action         => DBMS_REDACT.ENABLE
  );
  
  DBMS_OUTPUT.PUT_LINE('Policy re-enabled: SALARY_PARTIAL_REDACTION');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error managing policies: ' || SQLERRM);
END;
/

-- ============================================================================
-- Step 6: Drop Redaction Policies (Cleanup)
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('=== Step 6: Cleanup Instructions ===');
  DBMS_OUTPUT.PUT_LINE('');
  
  DBMS_OUTPUT.PUT_LINE('To remove all redaction policies:');
  DBMS_OUTPUT.PUT_LINE('');
  
  DBMS_OUTPUT.PUT_LINE('  -- Drop each policy');
  DBMS_OUTPUT.PUT_LINE('  EXECUTE DBMS_REDACT.DROP_POLICY(');
  DBMS_OUTPUT.PUT_LINE('    object_schema => ''REDACT_DEMO_USER'',');
  DBMS_OUTPUT.PUT_LINE('    object_name   => ''EMPLOYEES'',');
  DBMS_OUTPUT.PUT_LINE('    policy_name   => ''SSN_FULL_REDACTION''');
  DBMS_OUTPUT.PUT_LINE('  );');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('  -- Or drop the user and table');
  DBMS_OUTPUT.PUT_LINE('  DROP USER redact_demo_user CASCADE;');
  
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

-- ============================================================================
-- Summary
-- ============================================================================

BEGIN
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('========================================');
  DBMS_OUTPUT.PUT_LINE('Redaction Policies Summary');
  DBMS_OUTPUT.PUT_LINE('========================================');
  DBMS_OUTPUT.PUT_LINE('1. SSN_FULL_REDACTION: Full redaction (always hidden)');
  DBMS_OUTPUT.PUT_LINE('2. SALARY_PARTIAL_REDACTION: Partial redaction (show first 5 digits)');
  DBMS_OUTPUT.PUT_LINE('3. EMAIL_REGEX_REDACTION: Regex-based redaction');
  DBMS_OUTPUT.PUT_LINE('4. CC_HR_ONLY_REDACTION: Conditional (HR users only)');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Redaction Functions:');
  DBMS_OUTPUT.PUT_LINE('  - DBMS_REDACT.FULL: Hide all data');
  DBMS_OUTPUT.PUT_LINE('  - DBMS_REDACT.PARTIAL: Show partial data');
  DBMS_OUTPUT.PUT_LINE('  - DBMS_REDACT.REGEX: Pattern-based masking');
  DBMS_OUTPUT.PUT_LINE('  - DBMS_REDACT.EMPTY: Replace with empty string');
  DBMS_OUTPUT.PUT_LINE('  - DBMS_REDACT.NUMBER_PARTIAL: Partial number masking');
  DBMS_OUTPUT.PUT_LINE('');
  DBMS_OUTPUT.PUT_LINE('Key Points:');
  DBMS_OUTPUT.PUT_LINE('  - Redaction is real-time and transparent');
  DBMS_OUTPUT.PUT_LINE('  - Underlying data is never modified');
  DBMS_OUTPUT.PUT_LINE('  - Policies can be enabled/disabled dynamically');
  DBMS_OUTPUT.PUT_LINE('  - Expression controls which users see redacted data');
  DBMS_OUTPUT.PUT_LINE('========================================');
END;
/
